
title: Mark Alexander Williams
description: A simple Jekyll blog
url: "https://themarkness.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# Permalink structure
permalink: /:year/:month/:day/:title/

# Jekyll Archives
jekyll-archives:
  enabled:
    - tags
  layout: tag
  permalinks:
    tag: '/tag/:name/'

# Collections
collections:
  posts:
    output: true